language: node_js

node_js:
  - '8'

branches:
  only:
    - master

git:
  depth: 3
  quiet: true
  submodules: false

addons:
  ssh_known_hosts: 47.106.128.182

before_install:
  - openssl aes-256-cbc -K $encrypted_544cceae6566_key -iv $encrypted_544cceae6566_iv
    -in lianaishengdian.pem.enc -out lianaishengdian.pem -d
  - eval "$(ssh-agent -s)"
  - chmod 600 lianaishengdian.pem
  - ssh-add lianaishengdian.pem

install:
  - echo 'do some install'

script:
  - echo 'do some script'

after_success:
  - ssh root@47.106.128.182 "./deploy.sh"
